# Beginner Data Cleaning | Analysis | Visualization | Feature Engineering | Preprocessing | Model Evaluation

1. import & setup
2. load dataset's
3. basic Exploration
4. Data Cleaning
5. EDA
6. Correlation Analysis
7. Feature Engineering for ML
8. train_test_split
9. model evaluation

## 1. Impots & Setup

In [2]:
#Core
import pandas as pd
import numpy as np

#visualization
import seaborn as sns
import matplotlib.pyplot as plt

#ML
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#settings
pd.set_option('display.max_column', None)
sns.set(style= "whitegrid")

#handle warnings
import warnings
warnings.filterwarnings('ignore')

## 2. Load Dataset's

In [3]:
#load dataset's with 1k row and 5 columns
df= pd.read_csv('/kaggle/input/datasets/shaistashahid/freelancer-income-vs-skills/freelancer_earnings - freelancer_earnings_vs_skillstack_dataset.csv')

# df = df.sample(n=min(1000, len(df)), random_state=42)

df = df[['category', 'primary_skills', 'years_experience', 'hourly_rate_usd', 'annual_income_usd']]

df.head(5)

,category,primary_skills,years_experience,hourly_rate_usd,annual_income_usd
0,AI/ML Engineering,"Computer Vision, TensorFlow, Data Science",1.6,66.41,"$58,873.61"
1,Backend Development,"PHP, Ruby, Go",8.3,112.79,"$108,183.05"
2,UI/UX Design,"Sketch, Wireframing, Adobe XD",3.6,94.21,"$88,681.22"
3,DevOps,"Kubernetes, Terraform, AWS",2.3,118.87,"$109,229.42"
4,DevOps,"Azure, Docker, Kubernetes",8.8,82.76,"$66,298.22"

## 3. Basic Exploration

In [4]:
df.shape

(500, 5)

In [5]:
df.tail(5)

,category,primary_skills,years_experience,hourly_rate_usd,annual_income_usd
495,UI/UX Design,"Adobe XD, Sketch, Figma",9.7,129.08,"$114,149.16"
496,Cybersecurity,"Network Security, Security Audit, Cryptography",1.2,84.37,"$86,158.21"
497,DevOps,"Docker, Kubernetes, Terraform",6.4,220.15,"$225,178.75"
498,AI/ML Engineering,"Python, NLP, PyTorch",7.4,220.01,"$236,868.46"
499,Blockchain,"Ethereum, Solidity, Smart Contracts",10.8,127.68,"$136,126.59"

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           500 non-null    object
 1   primary_skills     500 non-null    object
 2   years_experience   500 non-null    float64
 3   hourly_rate_usd    500 non-null    float64
 4   annual_income_usd  500 non-null    object
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

In [7]:
df.describe()

       years_experience  hourly_rate_usd
count        500.000000       500.000000
mean           5.850000        97.149820
std            2.934779        52.697831
min            0.500000        17.280000
25%            3.600000        55.182500
50%            5.600000        84.445000
75%            7.800000       130.497500
max           14.000000       281.470000

In [8]:
#columns check
print('See the dataset colums')
print(df.columns)

See the dataset colums
Index(['category', 'primary_skills', 'years_experience', 'hourly_rate_usd',
       'annual_income_usd'],
      dtype='object')

In [9]:
print('Check The Null Value:-')
print(df.isnull().sum())

Check The Null Value:-
category             0
primary_skills       0
years_experience     0
hourly_rate_usd      0
annual_income_usd    0
dtype: int64

In [10]:
#categorical value check
df['primary_skills'].value_counts()

primary_skills
Network Security, Penetration Testing, Cryptography    6
Cryptography, Network Security, Security Audit         6
Security Audit, Cryptography, Penetration Testing      6
Security Audit, Cryptography, Network Security         5
Security Audit, Penetration Testing, Cryptography      5
                                                      ..
Ruby, Go, C#                                           1
Ruby, Java, C#                                         1
Kubernetes, Docker, AWS                                1
Python, Spark, BigQuery                                1
Android, React Native, iOS                             1
Name: count, Length: 377, dtype: int64

In [11]:
#categorical value check
df['category'].value_counts()

category
Cybersecurity          68
DevOps                 58
Web Development        58
Full Stack             51
UI/UX Design           48
Blockchain             46
Backend Development    45
AI/ML Engineering      45
Data Engineering       45
Mobile Development     36
Name: count, dtype: int64

In [12]:
#duplicated value found
print('Check the duplicated value:')
print(df.duplicated().sum())

Check the duplicated value:
0

## 4. Data Cleaning

In [13]:
#standardize column name
df.columns= df.columns.str.lower().str.replace(" ", "_")

#drop the duplicated columns
df.drop_duplicates(inplace= True)

#fix missing value
def safe_fill(df, cols, value= 'unknown', numeric= False):
    for col in cols:
        if df[col].isna().sum()> 0:
            if numeric:
                df[col]= df[col].fillna(df[col].median())
            else:
                df[col]= df[col].fillna(value)
    return df

#fix the categorical value space and /
df['category']= df['category'].str.lower().str.strip().str.replace('/', ' ', regex=True)
df['primary_skills']= df['primary_skills'].str.lower().str.strip().str.replace('/', ',', regex=True)

#clean the annual_income_usd
df['annual_income_usd']= pd.to_numeric(
    df['annual_income_usd'].str.replace(r'[$,]', '', regex= True), 
    errors= 'coerce'
)

## 5. Exploratory Data Analysis(EDA)