In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here are several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/masumauch/worldcity/world.csv

In [2]:
df = pd.read_csv("/kaggle/input/datasets/masumauch/worldcity/world.csv", on_bad_lines='skip')

In [3]:
# df = pd.read_csv("/kaggle/input/datasets/masumauch/worldcity/world.csv", sep=';')

## Data Analysis

In [4]:
df.head()

  ID            Name CountryCode       District  Population
0  1           Kabul         AFG          Kabol   1780000.0
1  2        Qandahar         AFG       Qandahar    237500.0
2  3           Herat         AFG          Herat    186800.0
3  4  Mazar-e-Sharif         AFG          Balkh    127800.0
4  5       Amsterdam         NLD  Noord-Holland    731200.0

In [5]:
df.sample(5)

        ID            Name CountryCode        District  Population
1353  1354          Nagaon         IND           Assam     93350.0
2761  2762             Ila         NGA      Oyo & Osun    264000.0
517    518        Basildon         GBR         England    100924.0
3427  3428  Dnipropetrovsk         UKR  Dnipropetrovsk   1103000.0
1464  1465          Milano         ITA       Lombardia   1300977.0

In [6]:
df.tail(5)

       ID     Name CountryCode District  Population
5059  ZMB   Tongan           F     11.0         NaN
5060  ZWE  English           T      2.2         NaN
5061  ZWE  Ndebele           F     16.2         NaN
5062  ZWE   Nyanja           F      2.2         NaN
5063  ZWE    Shona           F     72.1         NaN

In [7]:
df.shape

(5064, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5064 entries, 0 to 5063
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           5064 non-null   object
 1   Name         5064 non-null   object
 2   CountryCode  5064 non-null   object
 3   District     5060 non-null   object
 4   Population   4079 non-null   float64
dtypes: float64(1), object(4)
memory usage: 197.9+ KB

In [9]:
# df.isna().sum()[df.isna().sum()> 0]
print('Null Value of City:-')
print(df.isna().sum())

Null Value of City:-
ID               0
Name             0
CountryCode      0
District         4
Population     985
dtype: int64

In [10]:
#describe with population
df['Population'].describe()

count    4.079000e+03
mean     3.504682e+05
std      7.237757e+05
min      4.200000e+01
25%      1.147890e+05
50%      1.670510e+05
75%      3.106385e+05
max      1.050000e+07
Name: Population, dtype: float64

In [11]:
df['CountryCode'].value_counts()

CountryCode
F             746
CHN           363
IND           341
USA           274
BRA           250
             ...
WLF             1
VAT             1
VUT             1
VIR             1
IsOfficial      1
Name: count, Length: 235, dtype: int64

In [12]:
df.groupby('CountryCode')['Population'].sum().sort_values(ascending=False)

CountryCode
CHN           175953614.0
IND           123298526.0
BRA            85876862.0
USA            78625774.0
JPN            77965107.0
                 ...
TKL                 300.0
PCN                  42.0
F                     0.0
IsOfficial            0.0
T                     0.0
Name: Population, Length: 235, dtype: float64

In [13]:
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')